import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/learning_item.dart';
import '../domain/srs_scheduler.dart';
import '../data/learning_repository.dart';

part 'learning_providers.g.dart';

class LearningUiModel {
  const LearningUiModel({
    required this.items,
    required this.currentIndex,
    required this.revealedItemIds,
    this.isCompleted = false,
  });

  final List<LearningItem> items;
  final int currentIndex;
  final Set<String> revealedItemIds;
  final bool isCompleted;

  String get currentId {
    final item = items[currentIndex];
    if (item is WordItem) return item.word.id;
    if (item is GrammarItem) return item.grammar.id.toString();
    return '';
  }

  bool isRevealed(String id) => revealedItemIds.contains(id);

  double get progress {
    if (items.isEmpty) return 0;
    return (currentIndex + 1) / items.length;
  }

  LearningUiModel copyWith({
    List<LearningItem>? items,
    int? currentIndex,
    Set<String>? revealedItemIds,
    bool? isCompleted,
  }) {
    return LearningUiModel(
      items: items ?? this.items,
      currentIndex: currentIndex ?? this.currentIndex,
      revealedItemIds: revealedItemIds ?? this.revealedItemIds,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }

  static const LearningUiModel initial = LearningUiModel(
    items: [],
    currentIndex: 0,
    revealedItemIds: <String>{},
    isCompleted: false,
  );
}

@riverpod
class LearningNotifier extends _$LearningNotifier {
  @override
  FutureOr<LearningUiModel> build() async {
    final items = await ref.watch(learningRepositoryProvider).getLearningQueue();
    return LearningUiModel(
      items: items,
      currentIndex: 0,
      revealedItemIds: {},
    );
  }

  void onPageChanged(int index) {
    final value = state.valueOrNull;
    if (value == null || index < 0 || index >= value.items.length) {
      return;
    }
    state = AsyncData(value.copyWith(currentIndex: index));
  }

  void toggleReveal(String id) {
    final value = state.valueOrNull;
    if (value == null) return;

    final next = <String>{...value.revealedItemIds};
    if (next.contains(id)) {
      next.remove(id);
    } else {
      next.add(id);
    }
    state = AsyncData(value.copyWith(revealedItemIds: next));
  }

  Future<void> onRate(int score) async {
    final value = state.valueOrNull;
    if (value == null || value.isCompleted) return;

    final item = value.items[value.currentIndex];
    final String id;
    final String type;
    if (item is WordItem) {
      id = item.word.id;
      type = 'word';
    } else {
      id = (item as GrammarItem).grammar.id;
      type = 'grammar';
    }

    // Update progress in database
    await ref.read(learningRepositoryProvider).updateProgress(
      id,
      type,
      SrsRating.fromInt(score),
    );

    final isLast = value.currentIndex == value.items.length - 1;
    if (isLast) {
      state = AsyncData(value.copyWith(isCompleted: true));
    } else {
      state = AsyncData(value.copyWith(
        currentIndex: value.currentIndex + 1,
      ));
    }
  }
}

// The learningNotifierProvider will be generated by riverpod_generator.
